version: '3'
services:
  iotapi:
    image: iotapi
    build: .
    command: 'npm run start'
    ports:
      - '3001:3001'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
