name: Continuous Integration

on:
  pull_request:
    branches: [ development, staging, master ]

jobs:
    build_and_test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 #pull source code into virtual directory
        - uses: actions/setup-node@v1
          with:
            node-version: 14
        - run: npm ci
        - run: npm test
        - run: npm start:prod
