name: Continuous Integration

on:
  pull_request:
    branches: [ development, staging, master ]

jobs:
    build_and_test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 #pull source code into virtual directory
        - name: docker build
          run: |
            docker build -t iotapi -f Dockerfile.test  .